/**
 * Webview panel for displaying Rosetta HTML reports.
 *
 * Loads the self-contained HTML report generated by rosetta into
 * a VS Code webview panel.
 */

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

let currentPanel: vscode.WebviewPanel | undefined;

/**
 * Show an HTML report in a webview panel.
 *
 * @param htmlPath  Absolute path to the HTML report file.
 * @param title     Panel title.
 */
export function showReportWebview(htmlPath: string, title: string): void {
    const column = vscode.ViewColumn.Beside;

    if (currentPanel) {
        currentPanel.reveal(column);
    } else {
        currentPanel = vscode.window.createWebviewPanel(
            'rosettaReport',
            title,
            column,
            {
                enableScripts: true,
                retainContextWhenHidden: true,
                localResourceRoots: [
                    vscode.Uri.file(path.dirname(htmlPath)),
                ],
            },
        );
        currentPanel.onDidDispose(() => {
            currentPanel = undefined;
        });
    }

    currentPanel.title = title;

    try {
        let html = fs.readFileSync(htmlPath, 'utf-8');

        // Hide navigation links that don't work in Webview context
        const hideNavCSS = `<style>
a[href*="index.html"], a[href*="playground.html"], a[href*="whitelist.html"], a[href*="buglist.html"] { display: none !important; }
</style>`;

        const cspMeta = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: https:; script-src 'unsafe-inline'; style-src 'unsafe-inline';">`;

        html = html.replace('</head>', `${cspMeta}\n${hideNavCSS}\n</head>`);

        currentPanel.webview.html = html;
    } catch (e: any) {
        currentPanel.webview.html = `
            <html><body>
                <h2>Failed to load report</h2>
                <p>${e.message}</p>
                <p>Path: ${htmlPath}</p>
            </body></html>
        `;
    }
}

/**
 * Show SQL execution results in a webview panel.
 */
export function showExecResultWebview(result: Record<string, any>): void {
    const column = vscode.ViewColumn.Beside;

    const panel = vscode.window.createWebviewPanel(
        'rosettaExecResult',
        'SQL Execution Results',
        column,
        { enableScripts: true },
    );

    const results = result.results ?? {};
    const dbmsNames = Object.keys(results);

    // Build a simple comparison table
    let tableRows = '';
    const firstDbms = dbmsNames[0];
    const stmts = results[firstDbms]?.statements ?? [];

    for (let i = 0; i < stmts.length; i++) {
        const sql = stmts[i]?.sql ?? '';
        let cells = '';
        for (const name of dbmsNames) {
            const s = results[name]?.statements?.[i];
            if (!s) {
                cells += `<td class="cell">-</td>`;
                continue;
            }
            if (s.error) {
                cells += `<td class="cell error">ERROR: ${escapeHtml(s.error)}<br><span class="time">${s.elapsed_ms}ms</span></td>`;
            } else if (s.columns && s.rows) {
                const header = s.columns.join(' | ');
                const rows = s.rows.slice(0, 10).map((r: any[]) => r.join(' | ')).join('\n');
                const extra = s.rows.length > 10 ? `\n... +${s.rows.length - 10} rows` : '';
                cells += `<td class="cell"><pre>${escapeHtml(header)}\n${escapeHtml(rows)}${extra}</pre><span class="time">${s.elapsed_ms}ms</span></td>`;
            } else {
                cells += `<td class="cell ok">OK, ${s.affected_rows} rows<br><span class="time">${s.elapsed_ms}ms</span></td>`;
            }
        }
        tableRows += `<tr><td class="sql">${escapeHtml(sql)}</td>${cells}</tr>`;
    }

    const headerCells = dbmsNames.map(n => `<th>${escapeHtml(n)}</th>`).join('');

    panel.webview.html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 16px; color: var(--vscode-foreground); background: var(--vscode-editor-background); }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid var(--vscode-panel-border); padding: 8px; text-align: left; vertical-align: top; }
th { background: var(--vscode-editor-selectionBackground); }
.sql { font-family: monospace; font-size: 12px; max-width: 300px; word-break: break-all; }
.cell pre { margin: 0; font-size: 11px; white-space: pre-wrap; }
.cell.error { color: var(--vscode-errorForeground); }
.cell.ok { color: var(--vscode-testing-iconPassed); }
.time { font-size: 10px; opacity: 0.6; }
</style>
</head>
<body>
<h2>SQL Execution Results</h2>
<table>
<tr><th>SQL</th>${headerCells}</tr>
${tableRows}
</table>
</body>
</html>`;
}

function escapeHtml(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}
